app/components/Button.tsx
app/components/Card.tsx
app/models/mock-data.json
app/screens/ScheduleScreen/ScheduleDayPicker.tsx
app/screens/ScheduleScreen/ScheduleScreen.tsx
app/screens/WelcomeScreen.tsx
package.json
yarn.lock

[Screen: Schedule Screen](33-screen-schedule-screen)
- Does not close out the ticket, just adds the swiping functionality between lists
- Adds a horizontal FlatList for paging through daily schedules
- Animates day picker according to the horizontal scroll position
- Cleans up some Android specific styles
| iOS | Android |
| ![Simulator Screen Recording - iPhone 13 - 2022-11-21 at 14 53 50](https://user-images.githubusercontent.com/374022/203146537-d51be03d-bbc6-440a-9b6d-34d7be377d0e.gif) | <img src="https://user-images.githubusercontent.com/374022/203148280-26481cc4-8e0a-432b-b7fa-1adb7ec5e6e7.gif" width="280" /> |

feat(schedule-screen): swipe between schedules, animated day picker

---

app/components/Card.tsx
app/hooks/index.ts
app/hooks/useAppState.ts
app/models/SchedulesStore.ts
app/models/mock-data.json
app/screens/ScheduleScreen/ScheduleDayPicker.tsx
app/screens/ScheduleScreen/ScheduleScreen.tsx

[Screen: Schedule Screen](33-screen-schedule-screen)
- Upon pressing the day picker button, if the day is already selected, will scroll to top of the schedule list
- If the app is backgrounded or killed, the next time it is active we will scroll to the specific schedule for the current day when the conference is ongoing (both pre and post conference the user will just remain where they are) - the gif for this really doesn't show the traveling to the Desktop
| Top of list press | Backgrounded find correct day (pretend it's Thursday 😉) |
| <img src="https://user-images.githubusercontent.com/374022/203659088-df28cf90-1000-4069-bef4-f56cf5494714.gif" width="300" /> | <img src="https://user-images.githubusercontent.com/374022/203660394-e83935eb-334e-4ca8-8103-b4cd29f3053c.g …

feat(schedule-screen): return to active day during conference

---

.github/workflows/ci.yml

Setting tests/linter to run on push to any branch, but an EAS build to run on a push to `main` so the CI doesn't get so backlogged on PR updates.
Docs for reference:
- https://docs.github.com/en/actions/learn-github-actions/contexts#determining-when-to-use-contexts
- https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

fix(ci): create build on main branch push only

---

app/screens/TalkDetailsScreen/TalkDetailsScreen.tsx

[Trello Card](63-bug-shapes-on-talk-details-screen-fall-short-of-edge-on-larger-screens)
Fixes the large curved shapes on the Talk Details screen to make it to the edge of larger screens
| Before | After |
| ![Simulator Screen Shot - iPhone 14 Pro Max - 2022-12-13 at 14 24 51](https://user-images.githubusercontent.com/374022/207426858-c29069d1-701e-4857-926b-495b03211ea1.png) | ![Simulator Screen Shot - iPhone 14 Pro Max - 2022-12-13 at 14 24 34](https://user-images.githubusercontent.com/374022/207426906-ae571f26-6129-4b8d-a87a-fd3d65c1277e.png) |
| ![Simulator Screen Shot - iPhone 14 Pro Max - 2022-12-13 at 14 25 01](https://user-images.githubusercontent.com/374022/207426949-79354f43-e3ec-4f54-99a6-30275101a976.png) | ![Simulator Screen Shot - iPhone 14 Pro Max - …

fix(talk-details): large shapes screen width

---

app/screens/ScheduleScreen/ScheduleScreen.tsx
app/services/api/webflow-helpers.ts

Trello: 49-enhancement-center-schedule-list-around-the-current-ongoing-talk
Summary of the changes and any helpful notes for reviewers and testers. 
- Adds logic to center the ongoing talk card 
| iOS | Android |
|<video width="350" src="https://user-images.githubusercontent.com/53795920/207957039-57528b0f-4ec1-4065-86e7-8790ca0ef15f.mp4" />|<video width="350" src="https://user-images.githubusercontent.com/53795920/207957131-e9df6a49-ff5c-42d6-a0f3-500db2856b61.mp4" />|

feat: scroll to the proper time of day talk card

---

app.config.ts

The iOS status bar is by default dark text during splash start up, it doesn't convert over to the light color until the app actually starts and the status bar props are set.
I attempted to set the proper Info.plist value to have the light content at app start, however it didn't take.
This PR hides the status bar content (the dark text) during the initial splash screen and will get set properly to light content when the app begins. This will give it a more polished look than having hard to read dark text switch over to light text mid way through.
This is achieved by using the infoPlist key
or could have been done via config plugin too:
Config plugin (although unnecessary) for reference:

feat: hide dark status bar during splash

---

app/components/Button.tsx
app/components/Header.tsx
app/navigators/TabNavigator.tsx
app/screens/InfoScreen.tsx
app/screens/ScheduleScreen/ScheduleDayPicker.tsx
app/screens/VenueScreen/VenueScreen.tsx
app/screens/WelcomeScreen.tsx

Trello Card:
65-bug-large-font-size-breaks-styles-on-ios
66-bug-venuescreen-scrollbar-too-far-in-from-the-side
Summary of the changes and any helpful notes for reviewers and testers. 
- removes the vertical scroll indicator in the venue screen
- fixes broken styles with larger font sizes on iOS
| Before | After |
|<img width="300" alt="CleanShot 2022-12-19 at 15 37 23@2x" src="https://user-images.githubusercontent.com/53795920/208540322-b5fa1f6a-cd87-49c7-b721-9f71042b8448.png">|<img width="300" src="https://user-images.githubusercontent.com/53795920/208539789-f333b66e-0429-45bf-aca3-344c74a34229.png">|
|<img width="300" alt="CleanShot 2022-12-19 at 15 37 36@2x" src="https://user-images.githubusercontent.com/53795920/208540413-a772fab9-8273-4c45-9867-73149b6e58e6.png"> …

fix: remove scroll indicator and set max font scaling

---

app/components/Carousel.tsx

Stop over scroll from happening on Android so native on end bounce does not happen
| ![CleanShot 2023-01-13 at 12 19 53](https://user-images.githubusercontent.com/7799266/212391698-893bf54b-c822-45b2-b513-ec600be1a4fe.gif) | ![CleanShot 2023-01-13 at 12 17 36](https://user-images.githubusercontent.com/7799266/212391356-6d2bd4e6-2c00-4df4-bf73-3686df14ec94.gif) |

fix bounce animation: stop over scroll from happening

---

app/components/ButtonLink.tsx
app/components/Carousel.tsx
app/components/CarouselCard.tsx

Carousel should now scale to any amount of Carousel Items
| ![CleanShot 2023-01-18 at 09 48 48](https://user-images.githubusercontent.com/7799266/213258668-56c57edb-6e53-4ca6-925d-84190b9b9248.gif) | ![CleanShot 2023-01-18 at 09 50 14](https://user-images.githubusercontent.com/7799266/213258602-c1e0d2e5-d682-4c12-9071-abc4fb05dd7f.gif) |

carousel with an even split between items

---

app/screens/ScheduleScreen/ScheduleScreen.tsx

Replace nav header with the current schedule index date
| ![CleanShot 2023-01-19 at 14 22 21](https://user-images.githubusercontent.com/7799266/213552231-ae9dca3e-ad69-40e7-baaa-f9547f1a4d36.gif) | ![CleanShot 2023-01-19 at 14 21 31](https://user-images.githubusercontent.com/7799266/213552176-2ed0f75a-dd78-4152-8d11-064221da4895.gif) |

Replace nav header with current date

---

app/components/BoxShadow.tsx
app/components/Card.tsx
app/screens/ScheduleScreen/ScheduleCard.tsx
app/screens/ScheduleScreen/ScheduleScreen.tsx
app/services/api/webflow-helpers.ts

[Trello Card](88-update-schedule-card-styles-to-indicate-past-events)
Summary of the changes: 
- Check if the event already happened in the past then change card styles to indicate that is a past event.
|<video width="350" src="https://user-images.githubusercontent.com/53795920/214094970-20ddefe5-f138-45de-b0b7-cd1a999571e1.mp4" />|<video width="350" src="https://user-images.githubusercontent.com/53795920/214099618-0afae4fc-c0d7-4199-a6b3-046091d6dd32.mp4" />|

feat: change card styles to indicate past events

---

app/app.tsx
app/components/Button.tsx
app/i18n/en.ts
app/screens/ErrorScreen/ErrorBoundary.tsx
app/screens/ErrorScreen/ErrorDetails.tsx

[Trello Card](27-error-boundary-crash-resilience)
- Spruce up Error Detail screen with fun copy and link to GH with pre-filled issue template
- Fix reset button so it actually resets the navigation state 
| <img width="390" alt="Screen Shot 2023-01-24 at 3 55 34 PM" src="https://user-images.githubusercontent.com/6894653/214447321-eabf9b43-3b0e-49f0-9b16-b06934d1cc44.png">  |  <img width="357" alt="Screen Shot 2023-01-24 at 3 56 37 PM" src="https://user-images.githubusercontent.com/6894653/214447406-b01bb4ca-71ba-4908-8595-5ff761fc26e0.png"> |
| https://user-images.githubusercontent.com/6894653/214446603-594c8a71-65c4-48d8-8085-c2f5a04be23a.mp4 | https://user-images.githubusercontent.com/6894653/214446670-440743 …

Error boundary customization

---

app/screens/ScheduleScreen/ScheduleScreen.tsx
app/services/api/webflow-helpers.ts

[Trello Card](89-bug-delay-before-schedule-loads)
Refactor helper to expose `isLoading` when getting schedule data, and use that data to display an `ActivityIndicator` when appropriate.
| <video src="https://user-images.githubusercontent.com/1761481/214731732-6e9cd834-7798-4c4a-8094-534cb05dde6c.mp4" /> | <video src="https://user-images.githubusercontent.com/1761481/214739019-846dd359-6a5f-4a71-9d27-9adf10aab705.mp4" /> |

fix(schedule): Display ActivityIndicator when schedule is loading

---

app/screens/ScheduleScreen/ScheduleScreen.tsx

This was mistakenly added in #51

fix: Remove dangling console.tron.log call

---

README.md
eas.json

Update readme to not instruct installing an out of date version of `eas-cli`

fix(docs): Update readme

---

app/i18n/en.ts
app/screens/DebugScreen.tsx
app/services/api/webflow-helpers.ts

[Trello Card](93-add-full-state-reset-to-debug-screen)
Add 'Reset App State' button to clear async storage, reset react-query queries, reset navigation, and go to the welcome screen.
| <video src="https://user-images.githubusercontent.com/1761481/214989249-2ce70618-4cea-457b-89ae-bbd8828d1751.mp4" /> | <video src="https://user-images.githubusercontent.com/1761481/214989383-4b0c7e4c-6ed1-4b8a-a483-5f0c24e2bfbe.mp4" /> |

feat(debug): Add Reset State button to debug screen

---

app/screens/VenueScreen/VenueScreen.tsx
app/services/api/webflow-api.ts
app/services/api/webflow-api.types.ts
app/services/api/webflow-helpers.ts
app/services/reactotron/reactotron.ts

Trello Card: 112-bug-dont-include-past-sponsors
Summary of the changes:
- Added a helper `cleanedSponsors` to omit past sponsors before returning from the `useSponsors` hook
| Before| After 1| After 2|
|-|-|-|
|<img width="372" alt="CleanShot 2023-02-23 at 16 20 08@2x" src="https://user-images.githubusercontent.com/53795920/221235532-6e8382bc-d4ba-46e8-b5c9-239f20e58e90.png">| <img width="389" alt="CleanShot 2023-02-24 at 09 32 21@2x" src="https://user-images.githubusercontent.com/53795920/221235699-f3bc98e9-c69f-4fe7-bb22-73777007ff43.png">|<img width="385" alt="CleanShot 2023-02-24 at 09 32 40@2x" src="https://user-images.githubusercontent.com/53795920/221235754-38fe3538-9402-449c-99e4-3c9363d6b2a5.png">|

fix: no past sponsors

---

app/components/ScrollToButton.tsx
app/screens/ScheduleScreen/ScheduleScreen.tsx
app/screens/TalkDetailsScreen/SpeakerPanelScreen.tsx
app/services/reactotron/reactotron.ts

Trello Card: 114-bug-scroll-to-current-button-shows-up-when-navigating-to-a-different-screen-and-coming-back
Summary of the changes:
- Fixed the logic to show past event style only on the right date 
- Fixed the `scrollToCurrent` button that shows up when navigating to a different screen and coming back but ONLY on the first render. (iOS only)
|Before         | After          |
| <video width="350" src="https://user-images.githubusercontent.com/53795920/221019908-27a29eba-2b64-491a-a778-ba75dca0ec2d.mp4">|<video width="350" src="https://user-images.githubusercontent.com/53795920/221020291-82da19b3-7138-4644-993b-286968293fcd.mp4">|
|Before|After|
|-|-|
|<video width="350" src="https://user-images.githubusercontent.com/53795920/221021397-3807c1f8-122e …

fix: scroll to current button and logic to show past event style

---

app/components/ScrollToButton.tsx
app/screens/ScheduleScreen/ScheduleScreen.tsx

Summary of the changes:
- `scroll to current` button wasn't working on main and it's fixed.
|Before|After|
|-|-|
|<video width="250" src="https://user-images.githubusercontent.com/53795920/222233262-ec9bf9b6-c940-4d7e-9558-67eb9a0dfaeb.mp4">|<video width="250" src="https://user-images.githubusercontent.com/53795920/222233535-690bd1dd-4963-46d3-ac4c-1a7a4b204ed2.mp4">

fix: scroll-to-current button again

---

app/components/Header.tsx
app/components/carousel/CarouselCard.tsx
app/screens/DebugScreen.tsx
app/screens/ExploreScreen/ExploreScreen.tsx
app/screens/TalkDetailsScreen/TalkDetailsHeader.tsx

Trello Card: 
- 120-a11y-font-scaling-info-header-is-unreadable
- 121-a11y-font-scaling-debug-screen-needs-to-be-scrollable
- 122-a11y-font-scaling-long-talk-titles-overlap-text-on-talk-details-after-scrolling-down
- 123-a11y-font-scaling-map-illustration-link-cut-off
Summary of the changes 
- Font scaling issues that are mentioned in those Trello cards
- `Website` + `View on Map` link buttons on the `Food and Drink` carousel in Explore Screen
|120|121|122|123|
|-|-|-|-|
|<img width="200" src="https://user-images.githubusercontent.com/53795920/223545608-678a93c1-a3ba-43af-be0a-bdc6794b3b23.png">|<img width="200" src="https://user-images.githubusercontent.com/53795920/223545668-012bfd50-7607-4eec-94a3-7a4b0a131697.gif">|<img width="200" …

fix: font scaling

---

app/navigators/AppNavigator.tsx

- Set an initial route on the navigator since the screens are in alphabetical order now

specify initial route name for app navigator

---

app/components/carousel/CarouselCard.tsx
app/screens/InfoScreen.tsx
app/screens/ScheduleScreen/ScheduleCard.tsx

[Trello Card](139-the-last-item-in-carousel-has-additional-padding) — #96 
[Trello Card](137-title-of-schedule-card-is-overflowing-into-avatar-image) — #98 
[Trello Card](138-need-margins-between-title-and-carousel) — #97 
tackling 3 bugs in the PR:
1. title of schedule card is overflowing into avatar image #98
2. Need margins between title and carousel #97 
3. The last item in carousel has additional padding #96
| #97            | #98            | #96            |
| -------------- | ------------------ | ------------------ |
| <img width="250" src="https://user-images.githubusercontent.com/9324607/230459066-b0a88187-fd10-4c9b-bebc-3613cf1fa68a.png" /> | <img width="250" src="https://user-images.githubusercontent.com/9324607/230458945-036dcc4c-0c76-4fde-9dde-bbe865799b02.png" /> | <img …

(fix) tackling multiple bugs

---

app/components/carousel/Carousel.tsx
app/components/carousel/carousel.types.ts
app/i18n/en.ts
app/screens/ExploreScreen/ExploreScreen.tsx
app/services/api/webflow-consts.ts

[Trello Card](143-need-to-delete-this-info-from-explore) — #101 
[Trello Card](142-not-all-categories-made-it-to-the-app-on-explore) — #102 
[Trello Card](129-open-our-yelp-guide-kills-the-app) — #89 (we've removed the buttons altogether which fixes this) 
Restructuring the `Explore` screen to come from the CMS so @justinhuskey can control it
| <img width="300" src="https://user-images.githubusercontent.com/9324607/231275466-19018094-c499-4f66-85fd-578c2831887c.png" /> | <img width="300" src="https://user-images.githubusercontent.com/9324607/231275529-aa0ffcbf-7697-47cd-aed0-46c6aa7601fb.png" /> |

Explore Screen Updates

---

app.config.ts
app/services/api/axios.ts

This removes the Webflow API token from the app and instead points requests to an endpoint that proxies our requests to the Webflow API. This way, we do not leak secret in our client side bundle. The API endpoint has the Webflow token on the server and make requests to it on our behalf. It also caches the response from different collection endpoints to help with the API limit. The proxy server currently only fulfills requests to `/collections/*` to prevent using the token from searching for arbitrary endpoints
The previous token has been revoked, so we don't need to worry about scrubbing the git history.
[Trello Card](https://trello.com/c/W5iDohSh/155-remove-webflow-api-token)
n/a

Added Webflow proxy

---

app/screens/ScheduleScreen/ScheduleScreen.tsx
app/services/api/webflow-api.ts

On initial load, pull to refresh causes the refresh spinner to stick around instead of disappearing after the content is reloaded.
[Trello Card](159-infinispin-not-sure)
Fixes #131 
The `RefreshControl` had `refreshing` bound to `isLoading`. `isLoading` is only used for initial hard load. Using `refetch` would never update that state. Instead we are now binding `refreshing` to `isRefetching` to correctly indicate the status.
| <video src="https://user-images.githubusercontent.com/151139/233106938-3c63aa45-c344-4b6a-8846-cafb9c7520c5.mp4" /> | <video src="https://user-images.githubusercontent.com/151139/233107487-fd8a48ef-bb07-46c6-9982-9a6b2a973ec0.mp4" /> |
| | <video …

Fixing Infinispin on initial load

---

app/i18n/en.ts
app/screens/ScheduleScreen/ScheduleCard.tsx
app/screens/ScheduleScreen/ScheduleScreen.tsx
app/screens/VenuesScreen/VenuesScreen.tsx
app/services/api/webflow-api.types.ts
app/services/api/webflow-consts.ts
app/services/api/webflow-helpers.ts

[Trello Card](160-welcome-card) — #128 
[Trello Card](162-trivia-card) — #130 
[Trello Card](166-after-party-is-may-18-dont-include-the-19th) — #132 
[Trello Card](167-workshops-disclaimer) — #138 
Several changes here:
1. The `Welcome` card now better highlights our emcee, Ken LaFrance
2. The `Trivia Card` is now a thing (`variant` and all)
3. Fixed the After Party date on the `Venues` tab
4. Added a Workshops disclaimer on the `Wed` tab on the `Schedule` tab
| <img width="300" src="https://user-images.githubusercontent.com/9324607/233157523-9d23c3d0-3e83-40a1-ac4d-421456171c40.png" /><br/><img width="300" src="https://user-images.githubusercontent.com/9324607/233157658-925b71f8-1b84-4866-b55a-621574021131.png …

(fix) Schedule Cards

---

app/components/SocialButton.tsx
app/i18n/en.ts
app/screens/TalkDetailsScreen/AssistantsList.tsx
app/screens/TalkDetailsScreen/TalkDetailsScreen.tsx
app/utils/stringOrPlaceholder.ts

[Trello Card](172-when-data-is-missing-add-coming-soon-dont-leave-empty) — #136 
[Trello Card](171-sneaky-data-issues-missing-social-links) — #137 
- making sure talk screens have a "coming soon" label if empty
- updating how we're displaying socials
| <img src="https://user-images.githubusercontent.com/9324607/233375751-325c1568-8198-4fab-8ddb-e837ce44605b.png" width="300" /> | <img src="https://user-images.githubusercontent.com/9324607/233375889-984bf263-30e1-467d-8ff3-90c72c43bc0b.png" width="300" /> |

(fix) Talk Details screen

---

app.config.ts
app/components/ButtonLink.tsx
app/i18n/en.ts
app/screens/ExploreScreen/ExploreScreen.tsx
app/screens/InfoScreen/OurSponsorsScreen.tsx
app/services/api/webflow-helpers.ts
app/utils/customSort.ts
app/utils/groupBy.ts
app/utils/openLinkInBrowser.ts
app/utils/openMap.tsx

[Trello Card](154-explore-custom-sort-order) — #118 
[Trello Card](170-feature-request-advanced-map-link) — #133 
- adding a custom sort function for objects by its keys
- sorting the `Explore` tab
- Advanced Map Link on `Explore` tab (feature request)
| iOS | Android |
| ---- | ---- |
| <img width="300" src="https://user-images.githubusercontent.com/9324607/233421044-354d984f-406d-49c3-be11-3ecf1b4c513e.png" /> | <img width="300" src="https://user-images.githubusercontent.com/9324607/233420986-d3fb4d3a-3571-4c42-8901-081febb38b8c.png" />

(fix) `Explore` Custom Sort

---

app/screens/ExploreScreen/ExploreScreen.tsx
app/screens/InfoScreen/OurSponsorsScreen.tsx
app/screens/WelcomeScreen.tsx
app/services/api/webflow-api.ts
app/services/api/webflow-consts.ts
package.json
yarn.lock

[Trello Card](145-prefetch-event-schedule-on-app-load)
One of the benefits of React Query is that we can have patterns like pre-populating a query cache so it seems like a transition is "instant".
This PR separates out `queryKeys` and `queryFns` from hooks so that we can prefetch the event schedule queries on the initial welcome screen. That way, when the user clicks to the event schedule, it feels instantaneous because the data has already been fetched.
This PR also updates Prettier because the existing version had an issue parsing the `satisifies` TypeScript keyword. `yarn format` was also run which updated a few unrelated screens.
The webflow network request in "Before" occur only once the user navigates to the event schedule screen. Whereas the network requests in "After" occur as …

Prefetch event schedule data to improve initial load speed

---

app/navigators/AppNavigator.tsx

[Trello Card](175-android-white-flash-upon-navigating-sometimes) — #152
Updating theme on `AppNavigator` to have the right background color and not show a "white flash"
| <img src="https://user-images.githubusercontent.com/9324607/233721785-b25c9219-1d09-41a2-a5e3-13e602855a33.gif" width="300" /> | <img src="https://user-images.githubusercontent.com/9324607/233721782-b82f88d7-499e-4c85-a0f0-c3c1579b716a.gif" width="300" /> |

(fix) Android White Flash

---

app/screens/TalkDetailsScreen/TalkDetailsScreen.tsx

Removing Bios from the Trivia Show Panel carousel.
| <img width="473" alt="image" src="https://user-images.githubusercontent.com/151139/235946950-afafbd72-6f81-4734-8440-f49841b1f17f.png"> | <img width="478" alt="image" src="https://user-images.githubusercontent.com/151139/235947115-6a08fe7f-d1d2-4756-ad8c-d50298f57404.png"> |

Removing Bios from Trivia Show

---

app/screens/ScheduleScreen/ScheduleDayPicker.tsx
app/screens/ScheduleScreen/ScheduleScreen.tsx

This component was receiving all of the data we had for schedules when it only needed dates. Now if we need to change the structure of `schedules` the amount that this component cares about is surfaced at the component interface. We are now expecting these parameters to be of type `Date`. This sets the expectation for the caller.
_There were no graphical changes._

Refactor: Schedule Screen Day Picker Slider

---

app.config.ts
app/utils/openLinkInBrowser.ts

#207 
#208 
When an Android device has the app installed (Twitter), we have to explicitly deep link to it or it won't work. Also added a `mailto` intent to help with getting our email client working also

(fix) Open Links

---

app/components/ScrollToButton.tsx
app/i18n/en.ts

We missed some text in the app to add to our translations file. You can see this button by going through the following steps:
Change line 94 of ScheduleScreen.tsx from:
```typescript
const date = useCurrentDate()
```
to:
```typescript
const date = new Date("2023-05-18T21:00:00.000Z") // useCurrentDate()
```
This will manually move you into the middle of the second day. If you scroll up to previous events, you'll see this button appear.

Adding button text to i18n for scroll to button

---

app/screens/ScheduleScreen/ScheduleScreen.tsx

Setting the text container width so that the text will wrap properly. I'm not exactly sure as to why it isn't pulling the width from the container, but I have a feeling this will be more obvious when I refactor this into a `ScreenTab` component.
Note: Volume indicator is not relevant to the after screenshot. It's just there to show that I failed to take the screenshot the first time with one hand. I'm getting better at it, but more practice is evidently required. 😜 
| ![Screenshot_20230510_154247_Chain React App 2023](https://github.com/infinitered/ChainReactApp2023/assets/151139/4d796ba1-7e2d-4655-80d2-f3314db27d73) | ![Screenshot_20230510_153508_Chain React App …

Setting width on text container view for wrapping

---

app/navigators/AppNavigator.tsx

[Trello Card](190-android-safe-area-loses-background-color)
Fixes #217 
The navigationBar color was not set. It is now the beautiful color of `colors.background`.
| Before            | After             |
| ![Screenshot_20230510_145845_Chain React App 2023](https://github.com/infinitered/ChainReactApp2023/assets/151139/6c4640d8-b63d-4fa3-a15f-8ec2d74f5d41) | ![Screenshot_20230510_145356_Chain React App 2023](https://github.com/infinitered/ChainReactApp2023/assets/151139/579c63be-9d9b-4f72-8f88-31f9bb421c06) |
| <img width="466" alt="image" src="https://github.com/infinitered/ChainReactApp2023/assets/151139/5c6ec2b9-d705-486f-9668-e3474f5e9d40"> | <img width="469" alt="image" src="https://github.com/infinitered/ChainReactApp2023/assets/151139/4918d301 …

:bug: Adding navigation bar color for android

---

app/screens/ScheduleScreen/ScheduleScreen.tsx
app/services/api/webflow-api.ts

This is just a quick refactor so we aren't depending on _magic_ indexes for whether we show a banner on a particular schedule day.
No visual changes.

:recycle: Pushing banners down to the data layer

---

app/components/SocialButton.tsx

#227 
Adding some Accessibility Props to make sure our screen reader reads out the `SocialButtons` as expected

(fix) Adding Accessibility Props to `SocialButton`
