infinitered/ChainReactApp2023

app/i18n/en.ts
app/screens/InfoScreen.tsx
package.json
yarn.lock

[Trello Card](55-screen-info-screen)
- Moved email link button to right action component as per designs
- Code of conduct header from design change
- Added parallax animation to the carousel of images
| iOS |
| ------ |
| <img src="https://user-images.githubusercontent.com/374022/206725545-f5a0b408-bc28-450e-b54a-264941611399.png" width="300" /> |
| <img src="https://user-images.githubusercontent.com/374022/206725610-c3af179a-8deb-4b93-9dc8-1cb05ac3d003.png" width="300" /> |
| <img src="https://user-images.githubusercontent.com/374022/206725722-d60fb506-26a4-4577-a36a-da6125d0e850.gif"  width="300" /> |

fix(info-screen): design updates and animations

---

.github/pull_request_template.md

Updating our PR template to mention not including our Trello board "ID"
N/A

Fixing PR Remplate

---

eas.json

Use M1 workers for EAS iOS builds
Release blog post: https://blog.expo.dev/m1-workers-on-eas-build-dcaa2c1333ad

Use m1 for eas ios builds

---

app/components/CarouselCard.tsx
app/screens/VenueScreen/SponsorCard.tsx
app/screens/VenueScreen/VenueScreen.tsx
app/services/api/webflow-api.ts
app/services/api/webflow-api.types.ts
app/services/api/webflow-consts.ts
app/services/api/webflow-helpers.ts

[Trello Card](70-real-data-sponsors)
Summary of the changes: 
- Added and updated the `Sponsor` and `Venue` types
- Updated the venue screen to have real data
- Changed the gold sponsor logo size to be smaller than platinum's per design
- Changed the prop names of the `TierLevelProps` interface to match the CMS
https://user-images.githubusercontent.com/53795920/213507526-d1bc6935-caea-4ea5-a178-93737cfecdac.mp4

feat: venues and sponsors

---

.husky/pre-commit
.husky/pre-push
app/services/api/webflow-helpers.ts
package.json
yarn.lock

[Trello Card](92-add-husky-git-hook-to-run-linter-before-push)
* Run linter on staged files when committing. (Uses lint-staged, will automatically re-stage fixes before committing)
* Run linter on entire project when pushing (Will not automatically fix issues)
* Run tests when pushing

feat(git): Add pre-commit and pre-push hooks

---

app/components/Text.tsx
app/i18n/en.ts
app/screens/TalkDetailsScreen/TalkDetailsScreen.tsx

Assistants appearing for when a Workshop has assistants
Waiting on a couple questions to be answered from Jenna, and then will make adjustments accordingly!
| ![CleanShot 2023-01-27 at 16 59 57](https://user-images.githubusercontent.com/7799266/215221956-6ebf870d-7338-49c9-896b-87a4b033a478.png) | ![CleanShot 2023-01-27 at 16 58 43](https://user-images.githubusercontent.com/7799266/215221909-0a9f9f82-104b-4de7-bff7-93504caf0b32.png) |

Workshop Assistants

---

app/screens/VenueScreen/VenueScreen.tsx

Trello Card
106-add-loading-indicator-to-venue-screen
Summary of the changes 
- Adds loading indicator to venue tab
|<video width="350" src="https://user-images.githubusercontent.com/53795920/217084065-0911f787-ffa3-4479-8f87-0d91763664f9.mp4">|<video width="350" src="https://user-images.githubusercontent.com/53795920/217084155-d4fcbf24-c236-4e09-902d-a7cf852bd9a3.mp4">|

feat: add loading indicator to venue screen

---

app/app.tsx
app/services/reactotron/reactotron.ts

Just adding a few helpful Reactotron custom commands I worked through with @joshuayoes

(chore): add new Reactotron commands

---

app/screens/ScheduleScreen/ScheduleCard.tsx
app/utils/isConferencePassed.ts

updated isConferencedPassed to a function so it updates without app needing to be restarted, also took @jamonholmgren advice on just simplifying the function to compare to `new Date()` over using `isPast` 
After looking into isPast more it does seem overkill for this particular ask 🤔 (all date-fns get passed through [`toDate()`](https://github.com/date-fns/date-fns/blob/7e8026159b9496eddc3a683895d2e0566715d4bb/src/toDate/index.ts) which does some more work to provide consistency across browsers)

Update isConferencePassed to Function

---

app/components/Header.tsx
app/navigators/BackButton.tsx
app/screens/DebugScreen.tsx
app/screens/ScheduleScreen/ScheduleCard.tsx
app/screens/ScheduleScreen/ScheduleDayPicker.tsx
app/screens/ScheduleScreen/ScheduleScreen.tsx
app/screens/TalkDetailsScreen/TalkDetailsHeader.tsx

Some misc. accessibility fixes after initial screen reader review
- Create accessible grouping for break cards
- Switch accessibility focus when navigating to current event automatically
- Full day name as a11y label on day switcher buttons
- Re-usable back button component with a11y hint

Accessibility fixes

---

app/services/api/webflow-consts.ts

Fixes WebFlow API collection IDs after the site rework so data gets retrieved again

fix(webflow): updated collection ids

---

app/screens/ScheduleScreen/ScheduleScreen.tsx
app/screens/VenueScreen/SponsorCard.tsx
app/screens/VenueScreen/VenueScreen.tsx
app/services/api/webflow-api.ts

[Trello Card](131-bronze-silver-sponsors-not-clickable) — #88 
[Trello Card](132-pull-to-refresh) — #84 
- Making Silver Sponsors clickable
- ability to pull to refresh the schedule screen

(fix) pull to refresh &  clickable sponsors

---

app/services/reactotron/reactotron.ts
package.json
yarn.lock

[Trello Card](https://trello.com/c/7ieZoheL/144-add-reactotron-react-query)
Adds `reactotron-react-query` package along with configuration to wire it up.
https://user-images.githubusercontent.com/37849890/231322668-f039c453-afa9-426c-9f97-deab09c72ac4.mov

Add reactotron-react-query

---

app/screens/ErrorScreen/ErrorBoundary.tsx

Enabling `reportCrash` function in `ErrorBoundary` component to help with #83 issue.
N/A

Enable `reportCrash` on error

---

app/components/carousel/Carousel.tsx
app/components/carousel/carousel.types.ts
app/i18n/en.ts
app/screens/ExploreScreen/ExploreScreen.tsx
app/screens/InfoScreen/ContactUsScreen.tsx
app/screens/InfoScreen/InfoScreen.tsx
app/screens/InfoScreen/OurSponsorsScreen.tsx
app/screens/ScheduleScreen/ScheduleScreen.tsx
app/screens/VenuesScreen/VenuesScreen.tsx
app/screens/WelcomeScreen.tsx
app/services/api/webflow-consts.ts
app/utils/customSort.ts

[Trello Card](152-welcome-screen) — #110 
[Trello Card](151-venues-update-the-sort-order) — #111 
[Trello Card](150-info-sponsors-nasty-header-should-be-removed) — #112 
[Trello Card](149-info-contact-changes-to-headlines) — #113 
[Trello Card](148-info-should-contact-be-removed-from-top-right) — #114 
[Trello Card](147-explore-open-in-maps-consistency) — #115 
[Trello Card](146-explore-listed-items-should-be-a-carousel) — #116 
Wrapping up a bunch of bugs that @justinhuskey found while running through the app. See each Issue for more details.
| <img width="300" src="https://user-images.githubusercontent.com/9324607/231852895-2b8fcd22-636c-47c0-b11a-861ca4cdb7fe.png" /><br/><img …

(fix) Bug Bash with Justin

---

app/i18n/en.ts
app/navigators/InfoStackNavigator.tsx
app/screens/InfoScreen/CreditsScreen.tsx
app/screens/InfoScreen/InfoScreen.tsx

We wanted to make sure we recognized the all the folks who made this conference and app possible.
[Trello Card](161-credits) #127 
This creates another screen under the Info tab called "Credits".
| <img width="446" alt="image" src="https://user-images.githubusercontent.com/151139/233401428-67a18f8e-fe61-4d58-95b1-6bcf166664a5.png"> | <img width="415" alt="image" src="https://user-images.githubusercontent.com/151139/233401528-5fa2c5b6-cda8-4ea4-a657-605efec1eb73.png"> |
| <img width="440" alt="image" src="https://user-images.githubusercontent.com/151139/233401753-16373b03-a1a7-48b9-8eef-a3a3dcb2f300.png"> | <img width="410" alt="image" src="https://user-images.githubusercontent.com/151139/233401666-eefb8432-5f9c …

Adding Credits Screen

---

app/screens/ScheduleScreen/ScheduleCard.tsx
app/screens/TalkDetailsScreen/TalkDetailsScreen.tsx
app/services/api/webflow-api.types.ts

[Trello Card](165-day-2-after-lunch-talk-should-be-trivia-game) — #140 
Making `Trivia Show` card clickable and display like a multi-speaker talk page
| <img src="https://user-images.githubusercontent.com/9324607/233674423-15956085-d831-4b22-b612-e578ccadae69.png" width="300" /> | <img src="https://user-images.githubusercontent.com/9324607/233674398-7b1a939f-cae0-4332-bbda-212ac3966897.png" width="300" /> |

(fix) Trivia Page

---

app/components/Text.tsx

[Trello Card](177-fix-text-type-error)
n/a

Fix Text type

---

.maestro/AI.yaml
.maestro/subflows/ExpoDevClient.yaml
app/screens/ChatScreen/ChatScreen.tsx
app/screens/ScheduleScreen/ScheduleDayPicker.tsx
app/screens/ScheduleScreen/ScheduleScreen.tsx

Adding a Maestro test for our AI Chat feature to help with #163 
https://user-images.githubusercontent.com/9324607/234088515-5995ecaa-1fda-4caa-9a77-4bd80ec0cfcc.mp4

(feat) AI Maestro Flow

---

app/components/SocialButton.tsx
app/screens/TalkDetailsScreen/AssistantsList.tsx
app/screens/TalkDetailsScreen/TalkDetailsScreen.tsx
app/services/api/webflow-helpers.ts

[Trello Card](179-layout-issue-on-joshs-workshop-page) — #164 
updating how we lay out all our assistants on the workshop screen
| Before |
|--------|
| <img src="https://user-images.githubusercontent.com/9324607/234062326-ba9a991a-ecee-461e-8d76-07ad572ca93e.png" width="300" /> |
| <img src="https://user-images.githubusercontent.com/9324607/234061915-f16abd61-a583-4820-ac87-9dc403e7b02c.png" width="300" /><br/><img src="https://user-images.githubusercontent.com/9324607/234062082-08ad4b32-c25b-46f9-b3b9-983baaf00c66.png" width="300" /> | <img src="https://user-images.githubusercontent.com/9324607/234061981-939c4fe4-94a9-4999-939c-3dcf1d13d613.png" width="300" /><br/><img …

(fix) Workshop Assistants layout fix

---

app/config/config.base.ts

[Trello Card](130-constant-welcomes)
Fixes #83 - We were not persisting the navigation for all environments. 
| <video src="https://user-images.githubusercontent.com/151139/235168559-ad546e3e-f0d5-40f3-b6a2-543387cd0924.mp4" /> | <video src="https://user-images.githubusercontent.com/151139/235168965-166308bd-cf48-4b88-a33b-b4998cd93d6e.mp4" /> |

Fix Constant Welcomes

---

eas.json

Making sure our `production` android build type comes out as an APK

(fix) Android Build Type

---

app.config.ts

chore: APK setting and remove tablet support

---

app/screens/ScheduleScreen/ScheduleCard.tsx
app/services/api/webflow-helpers.ts

Handling schedule cards where the talk is TBD.
| <img width="471" alt="image" src="https://user-images.githubusercontent.com/151139/235981915-41506243-0425-41ce-81f6-5698183df9d4.png"> | <img width="466" alt="image" src="https://user-images.githubusercontent.com/151139/235981679-4061917a-ec09-4b02-b880-909adc3b2ed1.png"> |

Fixing TDB Schedule Cards

---

app.config.ts
package.json

bumping to `4.0.2` build # `7`

Version Bump for Release

---

app/i18n/en.ts

Updating text for sponsored break screens.
| <img width="480" alt="Screenshot 2023-05-16 at 8 27 24 AM" src="https://github.com/infinitered/ChainReactApp2023/assets/151139/b1dcdb29-728f-458e-81ab-fc7ac20f28d0"> | <img width="482" alt="Screenshot 2023-05-16 at 8 28 08 AM" src="https://github.com/infinitered/ChainReactApp2023/assets/151139/1d20b139-feb6-4bf5-9d73-eb456ee0dd32"> |
| ![Screenshot_20230516_114633_Chain React App 2023](https://github.com/infinitered/ChainReactApp2023/assets/151139/3748ace2-e5a4-4edc-b6ec-fbd2f892cf93) | ![Screenshot_20230516_114613_Chain React App 2023](https://github.com/infinitered/ChainReactApp2023/assets/151139/870fa07c-a9d7-4e5e-b8cb-9b5089e6543c) |

:pencil2: Update Text for break screens

---

app/components/Header.tsx
app/navigators/TabNavigator.tsx
app/screens/ScheduleScreen/ScheduleDay.tsx
app/screens/ScheduleScreen/ScheduleScreen.tsx
app/screens/TalkDetailsScreen/BreakDetailsScreen.tsx
app/screens/TalkDetailsScreen/TalkDetailsHeader.tsx
app/screens/TalkDetailsScreen/TalkDetailsScreen.tsx
app/screens/TalkDetailsScreen/WorkshopDetailsScreen.tsx
app/services/api/webflow-api.ts
app/theme/spacing.ts

This refactoring was for clarity, extracting out common values, and using proper height calculations for the `Flashlist`'s. This also moved each `ScheduleDay` into its own component for easier updating.
No visual changes.

:recycle: Refactor: Schedule Screen Days

---

app.config.ts
package.json

Version Bump for Release—8 (4.0.3)

---

app.config.ts
app/components/Button.tsx
app/screens/TalkDetailsScreen/TalkDetailsScreen.tsx
app/services/api/webflow-data.ts
app/theme/spacing.ts
package.json

Now that the talks have been posted, we've updated the `webflow-data.ts` file to include `talk-url` for all available talks.
Version bump is also included here
| <img src="https://github.com/infinitered/ChainReactApp2023/assets/9324607/843ba23e-2986-49dd-a5be-780be87e8711" width="300" /><br/><img src="https://github.com/infinitered/ChainReactApp2023/assets/9324607/c4cae99f-ea24-4beb-883c-f369cf426cc9" width="300" /> | <img src="https://github.com/infinitered/ChainReactApp2023/assets/9324607/d3897616-6ed5-4402-a303-4249a3f87b72" width="300" /><br/><img src="https://github.com/infinitered/ChainReactApp2023/assets/9324607/0476f1c6-5c87-4ebf-876b-b9b9e0114341" width="300" /> |

Adding Talk Links—9 (4.0.4)
